FROM python:3.9-alpine

# Add your application
COPY ./codee.py /app/test.py

# Copy and enable your CRON task
COPY ./crontab /app/mycron
RUN pip install requests mysql-connector-python
RUN crontab /app/mycron
# Create empty log (TAIL needs this)
RUN touch /tmp/out.log
# Start TAIL - as your always-on process (otherwise - container exits right after start)
CMD crond && tail -f /tmp/out.log